//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class workout_active
    {
        public int id { get; set; }
        public Nullable<int> workout_id { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.DateTime> starts_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public string comment { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual workout_collection workout_collection { get; set; }
    }
}
